name: Build PROJECT_MIMI macOS App + DMG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller flask psutil pywebview

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install frontend dependencies
      run: npm install
           npm install --save three
           npm install --save vanta

    - name: Build .app with PyInstaller
      run: |
        pyinstaller PROJECT_MIMI.spec --clean --noconfirm
        mkdir release
        cp -R dist/PROJECT_MIMI.app release/

    - name: Install create-dmg
      run: |
        brew install create-dmg

    - name: Create DMG
      run: |
        create-dmg \
          --volname "PROJECT_MIMI Installer" --window-pos 200 120 --window-size 500 300 --icon-size 100 --icon "PROJECT_MIMI.app" 125 140 --app-drop-link 375 140 "PROJECT_MIMI.dmg" release/

    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: PROJECT_MIMI-macOS-dmg
        path: PROJECT_MIMI.dmg
